name: example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/firebase_core
  firebase_core: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  easy_firebase_auth:
    path: ../

flutter:
  uses-material-design: true