name: easy_firebase_auth
description: Manage authentication with firebase in an extremely simple way
version: 3.2.0
homepage: https://lymtechx.com/
repository: https://github.com/lymtechx/easy_firebase_auth
issue_tracker: https://github.com/lymtechx/easy_firebase_auth/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^5.1.1
  # https://pub.dev/packages/sign_in_with_apple
  sign_in_with_apple: ^3.2.0
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^3.1.3
  # https://pub.dev/packages/crypto (Needed for Apple Sign In)
  crypto: ^3.0.1

  # https://pub.dev/packages/provider
  provider: ^5.0.0
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.4
  # https://pub.dev/packages/flutter_markdown
  flutter_markdown: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/easy_firebase_auth/graphics/google-logo.png
    - packages/easy_firebase_auth/graphics/apple_dark_icon.png
    - packages/easy_firebase_auth/graphics/apple_light_icon.png
    - packages/easy_firebase_auth/graphics/facebook_icon.png
