name: easy_firebase_auth
description: Manage authentication with firebase in an extremely simple way
version: 2.4.0
homepage: https://lymtechx.com/
repository: https://github.com/lymtechx/easy_firebase_auth
issue_tracker: https://github.com/lymtechx/easy_firebase_auth/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^4.5.1
  # https://pub.dev/packages/apple_sign_in
  apple_sign_in: ^0.1.0
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^0.18.1+2

  # https://pub.dev/packages/provider
  provider: ^4.3.2+2
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.4.2
  # https://pub.dev/packages/flutter_markdown
  flutter_markdown: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/easy_firebase_auth/graphics/google-logo.png
