name: easy_firebase_auth
description: Manage authentication with firebase in an extremely simple way
version: 1.0.8
homepage: https://lymtechx.com/
repository: https://github.com/lymtechx/easy_firebase_auth
issue_tracker: https://github.com/lymtechx/easy_firebase_auth/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^4.5.6
  apple_sign_in: ^0.1.0
  
  # was ^0.16.1
  firebase_auth: ^0.18.3
  

  flutter_facebook_login: ^3.0.0
  flutter_twitter: ^1.1.3

  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  flutter_markdown: ^0.5.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/easy_firebase_auth/graphics/google-logo.png
    - packages/easy_firebase_auth/graphics/facebook-logo.png
    - packages/easy_firebase_auth/graphics/twitter-logo.png
